# Generated by Django 4.0.4 on 2022-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relative',
            options={'verbose_name': 'Родственник', 'verbose_name_plural': 'Родственники'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AddField(
            model_name='relative',
            name='relative_type',
            field=models.CharField(blank=True, max_length=15, verbose_name='Степень родства'),
        ),
    ]
