# Generated by Django 4.0.4 on 2022-06-25 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_user', '0002_alter_relative_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='main_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Главный родитель'),
        ),
    ]
