# Generated by Django 4.0.4 on 2022-06-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_relative_main_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relative',
            options={'verbose_name': 'доверенное лицо', 'verbose_name_plural': 'доверенные лица'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'школа', 'verbose_name_plural': 'школы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'ученик', 'verbose_name_plural': 'ученики'},
        ),
    ]
